import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration202505262236281748273788995 implements MigrationInterface {
    name = 'Migration202505262236281748273788995'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "email" character varying(100) NOT NULL, "password" character varying(255) NOT NULL, "reset_token" text, "registration_date" TIMESTAMP NOT NULL DEFAULT now(), "last_login" TIMESTAMP DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."trading_points_type_enum" AS ENUM('Универмаг', 'Магазин', 'Киоск', 'Лоток')`);
        await queryRunner.query(`CREATE TABLE "trading_points" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "type" "public"."trading_points_type_enum" NOT NULL, "address" text NOT NULL, "size_sqm" numeric(10,2), "rent_cost" numeric(12,2), "utility_cost" numeric(12,2), "counter_count" integer, "floors_count" integer NOT NULL DEFAULT '1', "opening_date" date NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_5ae1b6fbd79b5b8d6cbf73815ad" UNIQUE ("name"), CONSTRAINT "PK_6a78152f83331e9991d843ab0ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "providers" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "phone" character varying(20), "email" character varying(100), "address" text NOT NULL, "active" boolean NOT NULL DEFAULT true, "registration_date" date NOT NULL DEFAULT ('now'::text)::date, CONSTRAINT "PK_af13fc2ebf382fe0dad2e4793aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."product_category" AS ENUM('None', 'Category1', 'Category2', 'Category3', 'Category4', 'Category5')`);
        await queryRunner.query(`CREATE TYPE "public"."measurement_type" AS ENUM('SingleUnit', 'Kilogram', 'Litre')`);
        await queryRunner.query(`CREATE TABLE "product_directory" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" text, "category" "public"."product_category" NOT NULL, "measurement" "public"."measurement_type" NOT NULL, "created_at" date NOT NULL DEFAULT now(), CONSTRAINT "PK_7c4fec3d0cb6363ffb63f9c55fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "providers_product_list" ("id" SERIAL NOT NULL, "price" numeric(12,2) NOT NULL, "minOrderQuantity" integer NOT NULL DEFAULT '1', "active" boolean NOT NULL DEFAULT true, "lastUpdate" TIMESTAMP NOT NULL DEFAULT now(), "provider_id" integer, "product_id" integer, CONSTRAINT "PK_229ce44a173ddb5708cfe3a300f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."order_status" AS ENUM('New', 'Shipped', 'Sent', 'Completed', 'Canceled')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" SERIAL NOT NULL, "order_date" TIMESTAMP NOT NULL DEFAULT now(), "status" "public"."order_status" NOT NULL, "total_cost" numeric(10,2) NOT NULL, "notes" text DEFAULT '', "provider_id" integer NOT NULL, CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" SERIAL NOT NULL, "order_id" integer NOT NULL, "product_id" integer NOT NULL, "quantity" integer NOT NULL, "price" numeric(12,2) NOT NULL, CONSTRAINT "positive_quantity" CHECK (quantity > 0), CONSTRAINT "positive_price" CHECK (price > 0), CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory" ("id" SERIAL NOT NULL, "trading_point_id" integer NOT NULL, "product_id" integer NOT NULL, "quantity" integer NOT NULL DEFAULT '0', "selling_price" numeric(12,2) NOT NULL, "last_update" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "positive_selling_price" CHECK (selling_price > 0), CONSTRAINT "PK_82aa5da437c5bbfb80703b08309" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."employee_role" AS ENUM('Role1', 'Role2', 'Role3', 'Role4', 'Role5')`);
        await queryRunner.query(`CREATE TABLE "employees" ("id" SERIAL NOT NULL, "full_name" character varying(100) NOT NULL, "role" "public"."employee_role" NOT NULL, "hire_date" date NOT NULL DEFAULT ('now'::text)::date, "base_salary" numeric(10,2) NOT NULL, "phone" character varying(20), "email" character varying(100), "active" boolean NOT NULL DEFAULT true, "trading_point_id" integer, CONSTRAINT "PK_b9535a98350d5b26e7eb0c26af4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."product_request_status" AS ENUM('New', 'Processed', 'Rejected')`);
        await queryRunner.query(`CREATE TABLE "product_requests" ("id" SERIAL NOT NULL, "request_date" TIMESTAMP NOT NULL DEFAULT now(), "status" "public"."product_request_status" NOT NULL, "notes" text DEFAULT '', "trading_point_id" integer NOT NULL, "employee_id" integer, CONSTRAINT "PK_95548600cf27dcc824033dea8cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_request_items" ("id" SERIAL NOT NULL, "quantity" integer NOT NULL, "request_id" integer NOT NULL, "product_id" integer, CONSTRAINT "PK_9a60ff45dcaa7f316ef1b80bf56" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "salaries" ("id" SERIAL NOT NULL, "employee_id" integer NOT NULL, "period_start" date NOT NULL, "period_end" date NOT NULL, "base_amount" numeric(12,2) NOT NULL, "bonus" numeric(12,2) NOT NULL DEFAULT '0', "tax" numeric(12,2) NOT NULL, "total_paid" numeric(12,2) NOT NULL, "payment_date" date NOT NULL, CONSTRAINT "valid_period" CHECK (period_end >= period_start), CONSTRAINT "PK_20ca60aa8d4201c7bcb430fdb36" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_transfers_status_enum" AS ENUM('запланирован', 'выполнен', 'отменен')`);
        await queryRunner.query(`CREATE TABLE "inventory_transfers" ("id" SERIAL NOT NULL, "source_point_id" integer NOT NULL, "destination_point_id" integer NOT NULL, "product_id" integer NOT NULL, "quantity" integer NOT NULL, "transfer_date" TIMESTAMP NOT NULL DEFAULT now(), "initiated_by" integer NOT NULL, "approved_by" integer, "status" "public"."inventory_transfers_status_enum" NOT NULL DEFAULT 'запланирован', CONSTRAINT "positive_quantity" CHECK (quantity > 0), CONSTRAINT "PK_0ab69c36e4239d5db7a3e149c31" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "department_store_sections" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "floor_number" integer NOT NULL, "trading_point_id" integer NOT NULL, "manager_id" integer, CONSTRAINT "PK_9856e28af4abb964f2a68cdb98f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "trading_point_halls" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "floor_number" integer NOT NULL DEFAULT '1', "size_sqm" numeric(10,2), "trading_point_id" integer NOT NULL, "section_id" integer, CONSTRAINT "PK_87b15502aa30ee1a96ef0945ec7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "halls_assignment" ("id" SERIAL NOT NULL, "employee_id" integer, "hall_id" integer, CONSTRAINT "PK_e37d7756760da1f0ecf744584d4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" SERIAL NOT NULL, "full_name" character varying NOT NULL, "phone_number" character varying, "registration_date" TIMESTAMP NOT NULL DEFAULT now(), "birthday" date, "notes" text, CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sales_payment_method_enum" AS ENUM('наличные', 'карта', 'сбп', 'крипта', 'другое')`);
        await queryRunner.query(`CREATE TABLE "sales" ("id" SERIAL NOT NULL, "trading_point_id" integer NOT NULL, "employee_id" integer NOT NULL, "customer_id" integer, "sale_date" TIMESTAMP NOT NULL DEFAULT now(), "total_amount" numeric(14,2) NOT NULL, "payment_method" "public"."sales_payment_method_enum" NOT NULL DEFAULT 'наличные', CONSTRAINT "PK_4f0bc990ae81dba46da680895ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sale_items" ("id" SERIAL NOT NULL, "sale_id" integer NOT NULL, "product_id" integer NOT NULL, "quantity" integer NOT NULL, "price" numeric(12,2) NOT NULL, CONSTRAINT "positive_quantity" CHECK (quantity > 0), CONSTRAINT "positive_price" CHECK (price > 0), CONSTRAINT "PK_5a7dc5b4562a9e590528b3e08ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "providers_product_list" ADD CONSTRAINT "FK_4ae147d4831ec4a56cabd36a596" FOREIGN KEY ("provider_id") REFERENCES "providers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "providers_product_list" ADD CONSTRAINT "FK_e55e8948ae65051b0f0ac976832" FOREIGN KEY ("product_id") REFERENCES "product_directory"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_e4a8190cedd491dd878e3195baa" FOREIGN KEY ("provider_id") REFERENCES "providers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9263386c35b6b242540f9493b00" FOREIGN KEY ("product_id") REFERENCES "product_directory"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_811df61b324ab547f7b7ded71ba" FOREIGN KEY ("trading_point_id") REFERENCES "trading_points"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_732fdb1f76432d65d2c136340dc" FOREIGN KEY ("product_id") REFERENCES "product_directory"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_03affb72f9b20b7b171e44be69a" FOREIGN KEY ("trading_point_id") REFERENCES "trading_points"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_requests" ADD CONSTRAINT "FK_5aeba3cd6edfc437586e4d0e424" FOREIGN KEY ("trading_point_id") REFERENCES "trading_points"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_requests" ADD CONSTRAINT "FK_451cb415b15add7a79921562e6c" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_request_items" ADD CONSTRAINT "FK_35b8869be2d8e096d1e8c2c2f69" FOREIGN KEY ("request_id") REFERENCES "product_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_request_items" ADD CONSTRAINT "FK_7fa670d5f6dfc33503cc49f2ca7" FOREIGN KEY ("product_id") REFERENCES "product_directory"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salaries" ADD CONSTRAINT "FK_9ac79195d31e77bb6df432eab13" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transfers" ADD CONSTRAINT "FK_8a3931cbd96e7e67a1de7d62228" FOREIGN KEY ("source_point_id") REFERENCES "trading_points"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transfers" ADD CONSTRAINT "FK_2e1b9dee58f28c580ed24089542" FOREIGN KEY ("destination_point_id") REFERENCES "trading_points"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transfers" ADD CONSTRAINT "FK_a609b4f8983ccaaf9c5969286de" FOREIGN KEY ("product_id") REFERENCES "product_directory"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transfers" ADD CONSTRAINT "FK_3f60360f156162e9fea7f1b3893" FOREIGN KEY ("initiated_by") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transfers" ADD CONSTRAINT "FK_9684cb0ae2225865b75fc4620aa" FOREIGN KEY ("approved_by") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "department_store_sections" ADD CONSTRAINT "FK_9a92e3508126da1b1f94dc561c3" FOREIGN KEY ("trading_point_id") REFERENCES "trading_points"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "department_store_sections" ADD CONSTRAINT "FK_fccf50cc945113738dc1c280402" FOREIGN KEY ("manager_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trading_point_halls" ADD CONSTRAINT "FK_6eeb592795c6cc3ff5ed0a05c13" FOREIGN KEY ("trading_point_id") REFERENCES "trading_points"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trading_point_halls" ADD CONSTRAINT "FK_0b1a4231c26f74681f6fd8bf23d" FOREIGN KEY ("section_id") REFERENCES "department_store_sections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "halls_assignment" ADD CONSTRAINT "FK_0dc5f3e5ba470543d262c234d98" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "halls_assignment" ADD CONSTRAINT "FK_058214933d64850c83eea100bdc" FOREIGN KEY ("hall_id") REFERENCES "trading_point_halls"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_664179169563c3afe1f64426347" FOREIGN KEY ("trading_point_id") REFERENCES "trading_points"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_731ffab2e5e639ef1326117c17b" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_c51005b2b06cec7aa17462c54f5" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "FK_c210a330b80232c29c2ad68462a" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "FK_4ecae62db3f9e9cc9a368d57adb" FOREIGN KEY ("product_id") REFERENCES "product_directory"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "FK_4ecae62db3f9e9cc9a368d57adb"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "FK_c210a330b80232c29c2ad68462a"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_c51005b2b06cec7aa17462c54f5"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_731ffab2e5e639ef1326117c17b"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_664179169563c3afe1f64426347"`);
        await queryRunner.query(`ALTER TABLE "halls_assignment" DROP CONSTRAINT "FK_058214933d64850c83eea100bdc"`);
        await queryRunner.query(`ALTER TABLE "halls_assignment" DROP CONSTRAINT "FK_0dc5f3e5ba470543d262c234d98"`);
        await queryRunner.query(`ALTER TABLE "trading_point_halls" DROP CONSTRAINT "FK_0b1a4231c26f74681f6fd8bf23d"`);
        await queryRunner.query(`ALTER TABLE "trading_point_halls" DROP CONSTRAINT "FK_6eeb592795c6cc3ff5ed0a05c13"`);
        await queryRunner.query(`ALTER TABLE "department_store_sections" DROP CONSTRAINT "FK_fccf50cc945113738dc1c280402"`);
        await queryRunner.query(`ALTER TABLE "department_store_sections" DROP CONSTRAINT "FK_9a92e3508126da1b1f94dc561c3"`);
        await queryRunner.query(`ALTER TABLE "inventory_transfers" DROP CONSTRAINT "FK_9684cb0ae2225865b75fc4620aa"`);
        await queryRunner.query(`ALTER TABLE "inventory_transfers" DROP CONSTRAINT "FK_3f60360f156162e9fea7f1b3893"`);
        await queryRunner.query(`ALTER TABLE "inventory_transfers" DROP CONSTRAINT "FK_a609b4f8983ccaaf9c5969286de"`);
        await queryRunner.query(`ALTER TABLE "inventory_transfers" DROP CONSTRAINT "FK_2e1b9dee58f28c580ed24089542"`);
        await queryRunner.query(`ALTER TABLE "inventory_transfers" DROP CONSTRAINT "FK_8a3931cbd96e7e67a1de7d62228"`);
        await queryRunner.query(`ALTER TABLE "salaries" DROP CONSTRAINT "FK_9ac79195d31e77bb6df432eab13"`);
        await queryRunner.query(`ALTER TABLE "product_request_items" DROP CONSTRAINT "FK_7fa670d5f6dfc33503cc49f2ca7"`);
        await queryRunner.query(`ALTER TABLE "product_request_items" DROP CONSTRAINT "FK_35b8869be2d8e096d1e8c2c2f69"`);
        await queryRunner.query(`ALTER TABLE "product_requests" DROP CONSTRAINT "FK_451cb415b15add7a79921562e6c"`);
        await queryRunner.query(`ALTER TABLE "product_requests" DROP CONSTRAINT "FK_5aeba3cd6edfc437586e4d0e424"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_03affb72f9b20b7b171e44be69a"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_732fdb1f76432d65d2c136340dc"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_811df61b324ab547f7b7ded71ba"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9263386c35b6b242540f9493b00"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_e4a8190cedd491dd878e3195baa"`);
        await queryRunner.query(`ALTER TABLE "providers_product_list" DROP CONSTRAINT "FK_e55e8948ae65051b0f0ac976832"`);
        await queryRunner.query(`ALTER TABLE "providers_product_list" DROP CONSTRAINT "FK_4ae147d4831ec4a56cabd36a596"`);
        await queryRunner.query(`DROP TABLE "sale_items"`);
        await queryRunner.query(`DROP TABLE "sales"`);
        await queryRunner.query(`DROP TYPE "public"."sales_payment_method_enum"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "halls_assignment"`);
        await queryRunner.query(`DROP TABLE "trading_point_halls"`);
        await queryRunner.query(`DROP TABLE "department_store_sections"`);
        await queryRunner.query(`DROP TABLE "inventory_transfers"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_transfers_status_enum"`);
        await queryRunner.query(`DROP TABLE "salaries"`);
        await queryRunner.query(`DROP TABLE "product_request_items"`);
        await queryRunner.query(`DROP TABLE "product_requests"`);
        await queryRunner.query(`DROP TYPE "public"."product_request_status"`);
        await queryRunner.query(`DROP TABLE "employees"`);
        await queryRunner.query(`DROP TYPE "public"."employee_role"`);
        await queryRunner.query(`DROP TABLE "inventory"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."order_status"`);
        await queryRunner.query(`DROP TABLE "providers_product_list"`);
        await queryRunner.query(`DROP TABLE "product_directory"`);
        await queryRunner.query(`DROP TYPE "public"."measurement_type"`);
        await queryRunner.query(`DROP TYPE "public"."product_category"`);
        await queryRunner.query(`DROP TABLE "providers"`);
        await queryRunner.query(`DROP TABLE "trading_points"`);
        await queryRunner.query(`DROP TYPE "public"."trading_points_type_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
